### ISSUE TITLE
Add support to upload files from CDN

### ISSUE THREAD

**Issue by miranda90jose** [Bynder/bynder-php-sdk#17]
I am trying to upload a file from external source (CDN) to bynder but it looks like the functionality breaks as the following code from uploadFile() does not work for external URL's. 
 $fileSize = filesize($data['filePath']);

Is there any workaround available for this?

**Comment by condemil** [comment]
In your code you can do HTTP `GET` or `OPTIONS` call to external CDN url. The file size will be in `Content-Length` HTTP header.

**Comment by danielsequeira** [comment]
also our current implementation of `uploadFile()` doesn't support uploading files directly from an URL, you would need to write some logic to download the file and then when you have it, pass its `filePath` to the `uploadFile()` method.
