### ISSUE TITLE
OAuth1a support dropped?

### ISSUE THREAD

**Issue by noofaq** [Bynder/bynder-php-sdk#19]
According to the docs - https://bynder.docs.apiary.io/#reference/oauth-1.0a - OAuth 1.0a does not seem to be deprecated. Is there a reason why support for it was dropped in this package?
It seems that BynderSDK 1.x branch works just fine.

Our current application uses background server-to-server connection with Bynder and does not allow user to use proper OAuth2 flow as there is no frontend in that part. Additionally the process goes for a longer time so even adding basic OAuth2 authorization would not solve the need as we cannot ask user to login again and again to keep connection valid.

**Comment by danielsequeira** [comment]
For the newest release/tag 2.0.0 of the SDK OAuth 1.0a support was removed, this new release only supports OAuth 2.0.

This is due to the fact that in the long term we do want to deprecate OAuth 1.0a in Bynder and only use OAuth 2.0. At the moment we don't have an official plan and timeline for the deprecation, which might still take a while.

In the meantime to still make use of OAuth 1.0a, you will need to use one of the previous releases/tags.

**Comment by noofaq** [comment]
@danielsequeira Thank you for the information

Can you suggest how OAuth 1,0a should be replaced with longterm server-to-server communication required in our application? 
I guess tokens from OAuth2 would not be permanent (or at least long term in terms of weeks/months) so our application would lose connection after some short time (even if we somehow add UI just to setup connection with Bynder). I don't see it acceptable to call user every few hours just to login. Using headless browser to simulate such action automatically would be less secure as currently we don't store user passwords anywhere.

**Comment by danielsequeira** [comment]
@noofaq you're welcome.

Regarding server-to-server communication we are currently implementing permanent tokens functionality for our OAuth2 service. I can't give a precise date when this will be released, but it should be available in the next few weeks.

Currently the access tokens generated by our OAuth2 service expire in 1h, but we do offer the possibility for you to request refresh tokens which are permanent and can be used to generate new access tokens.
