### ISSUE TITLE
api/v4/tags query regularly exceed timeout

### ISSUE THREAD

**Issue by davereid** [Bynder/bynder-php-sdk#23]
We are seeing issues with the call to api/v4/tags often exceed a 20/30 second timeout.

**Comment by davereid** [comment]
I am attempting to gather data about how often the request fails, if it's at certain times, etc.

**Comment by danielsequeira** [comment]
hey @davereid, which Bynder account are you querying?

**Comment by Arpit-Sharma-USC** [comment]
Closing due to lack of movement on the issue. Feel free to reach out if you need help with something @davereid!

**Comment by davereid** [comment]
This hasn't been resolved at all. We've had to enable workarounds to account for this, and the tag APIs have been further limited in functionality by not being able to exclude tags without any asset usage.

**Comment by Arpit-Sharma-USC** [comment]
@davereid Can you tell me which Bynder account you are querying? It can help us verify this behaviour on our side.
