### ISSUE TITLE
Non utf-8 characters

### ISSUE THREAD

**Issue by Vashenm** [Bynder/bynder-php-sdk#26]
<img width="209" alt="Screenshot 2020-03-24 at 07 43 03" src="https://user-images.githubusercontent.com/37084453/77392965-c9725980-6da4-11ea-95ea-32d6c83dab24.png">

Hi, I am getting not utf-8 characters returned.

**Comment by TimBloembergen** [comment]
@Vashenm Could you give some more details as in how and where you are receiving this? Thanks!
