### ISSUE TITLE
Oauth 2.0 Authentication method.

### ISSUE THREAD

**Issue by kilis** [Bynder/bynder-php-sdk#27]
Hello!

I have an question related to bynder authentication via SDK.
How i can achieve authentication with refresh tokens. Is it possible to have a working code example?
Thanks!

**Comment by TimBloembergen** [comment]
Hi Kilis,

In our Sample file we have included an OAuth2 example, you can find it here: https://github.com/Bynder/bynder-php-sdk/blob/8838ecaa7da43c2820bfd36c344d505948d190ae/sample/sample.php#L8-L55
