### ISSUE TITLE
No Way to Add Header keys and values

### ISSUE THREAD

**Issue by pmaine** [Bynder/bynder-php-sdk#5]
I work in a large corporation and I need to be able to add header keys and values - How can I do this with the PHP SDK?

**Comment by jfcsantos** [comment]
Hi there! Have you checked the [Guzzle Docs](http://docs.guzzlephp.org/en/latest/request-options.html) for that? I'm planning to add more flexibility to the requests but if you need it urgently it won't be hard to implement.

**Comment by jfcsantos** [comment]
Hi there @pmaine. Can you checkout the new release of the SDK and see if that works for you?
You can pass any parameter available in the [Guzzle Request options](http://docs.guzzlephp.org/en/latest/request-options.html) when you create the BynderApi object - see the [README](https://github.com/Bynder/bynder-php-sdk/blob/master/README.md) for an example.
