### ISSUE TITLE
Possibility to create a metaproperty option using the SDK

### ISSUE THREAD

**Issue by Crovitche-1623** [Bynder/bynder-php-sdk#61]
I haven't found the method or it doesn't exist.

see: https://bynder.docs.apiary.io/#reference/metaproperties/metaproperty-option-operations/create-metaproperty-option

**Comment by TimBloembergen** [comment]
Hi @Crovitche-1623 the SDK currently does not support creating new metaproperty options Currently the team has other high priority work I cannot prioritise updating the SDK to support this new method. What you could do is create a PR with the necessary code changes yourself as this is an opensource project, we can review and release a new SDK version if the code is up to our standards.
