### ISSUE TITLE
Possibility to upload the asset as a new version using the SDK

### ISSUE THREAD

**Issue by Crovitche-1623** [Bynder/bynder-php-sdk#62]
I haven't figured out how to do it, or it's simply not possible at this stage with the SDK.

see: https://bynder.docs.apiary.io/#reference/upload-assets/6-saving-a-completed-upload/save-as-a-new-asset-version

**Comment by ahongbynder** [comment]
@Crovitche-1623 Existing PHP SDK also doesn't have a method to do that, thus also requiring it to be implemented. @TimBloembergen can confirm as well when he's back and available.

cc: @thegreatdeku

**Comment by TimBloembergen** [comment]
Hi @Crovitche-1623 the SDK currently does not support uploading an asset as a new version. Currently the team has other high priority work I cannot prioritise updating the SDK to support this new method. What you could do is create a PR with the necessary code changes yourself as this is an opensource project, we can review and release a new SDK version if the code is up to our standards.
