### ISSUE TITLE
getMetaproperties no longer works 

### ISSUE THREAD

**Issue by Jibz1** [Bynder/bynder-php-sdk#7]
getMetaproperties() from assetBankManager doesn't work anymore. 

Plus this shows
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in ../Bynder/Api/Impl/Oauth/OauthRequestHandler.php on line 165

**Comment by jfcsantos** [comment]
I'm guessing this issue was the one reported to support, it's related to the API and the amount of data retrieved, nothing we can do in the SDK. 

Closing this for now.
